<a href="https://colab.research.google.com/github/Bhavya0304/ML-AI-Collabs/blob/main/NeuralNetworkWithPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from torch import nn
import torch
import numpy as np
from torch import optim
from torchvision.datasets import MNIST

In [ ]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cpu device


In [ ]:
data = MNIST(download=True,root="data",train=True)

In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [ ]:
X =  torch.tensor(data.train_data,dtype=torch.float32)
Y = data.train_labels
X[0]

/usr/local/lib/python3.10/dist-packages/torchvision/datasets/mnist.py:76: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
<ipython-input-144-62c6bab2fe4e>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X =  torch.tensor(data.train_data,dtype=torch.float32)
/usr/local/lib/python3.10/dist-packages/torchvision/datasets/mnist.py:66: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,

In [ ]:
np.array(Y).reshape(10,)

ValueError: cannot reshape array of size 60000 into shape (10,)

In [ ]:

def oneHot(arr1):
  arr = np.zeros((arr1.shape[0],10),dtype=float)
  arr[np.arange(arr1.shape[0]),list(np.array(arr1.reshape(arr1.shape[0],),dtype=int))] = 1
  return arr

In [ ]:

print(Y)

def one_hot(a, num_classes):
  return np.squeeze(np.eye(num_classes)[a.reshape(-1)])

tensor([5, 0, 4,  ..., 5, 6, 8])


In [ ]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): Sigmoid()
  )
)


In [ ]:
# train the model
loss_fn   = nn.BCELoss()  # binary cross entropy
optimizer = optim.Adam(model.parameters(), lr=0.001)

n_epochs = 20
batch_size = 100


(X/100).dtype

torch.float32

In [ ]:
for epoch in range(n_epochs):
    for i in range(0, len(X), batch_size):
        Xbatch = X[i:i+batch_size]
        y_pred = model(Xbatch)
        ybatch = Y[i:i+batch_size]
        ybatch = torch.from_numpy(oneHot(ybatch).astype('float32'))
        loss = loss_fn(y_pred, ybatch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f'Finished epoch {epoch}, latest loss {loss}')

Finished epoch 0, latest loss 0.046600326895713806
Finished epoch 1, latest loss 0.030214762315154076
Finished epoch 2, latest loss 0.02997829020023346
Finished epoch 3, latest loss 0.018080737441778183
Finished epoch 4, latest loss 0.021910399198532104
Finished epoch 5, latest loss 0.015561865642666817
Finished epoch 6, latest loss 0.013511567376554012
Finished epoch 7, latest loss 0.012382617220282555
Finished epoch 8, latest loss 0.015688376501202583
Finished epoch 9, latest loss 0.01064440980553627
Finished epoch 10, latest loss 0.013909978792071342
Finished epoch 11, latest loss 0.005426696501672268
Finished epoch 12, latest loss 0.006087190471589565
Finished epoch 13, latest loss 0.008845156989991665
Finished epoch 14, latest loss 0.01569445990025997
Finished epoch 15, latest loss 0.006562783848494291
Finished epoch 16, latest loss 0.023698655888438225
Finished epoch 17, latest loss 0.007537452038377523
Finished epoch 18, latest loss 0.0073442100547254086
Finished epoch 19, lates

In [ ]:
Xtest =  torch.tensor(data.test_data,dtype=torch.float32)
Ytest = data.test_labels
Y1 = data.train_labels
y_pred = model(Xtest)
ans = []
y_pred[y_pred.round() == 1]
# for i in range(0,Ytest.shape[0]):
with torch.no_grad():
  y_pred = model(Xtest)
#   ans.append(np.array(Ytest[i]).reshape(1,) == np.array(np.where(y_pred.round()==1)[0]))


<ipython-input-71-249c28e8acd7>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  Xtest =  torch.tensor(data.test_data,dtype=torch.float32)


In [ ]:
y_pred.argmax(1)

tensor([5, 0, 4,  ..., 5, 6, 8])

In [ ]:
model.load_state_dict(torch.load("/content/params.pt"))

RuntimeError: Error(s) in loading state_dict for NeuralNetwork:
	Missing key(s) in state_dict: "linear_relu_stack.1.weight", "linear_relu_stack.1.bias". 
	Unexpected key(s) in state_dict: "linear_relu_stack.4.weight", "linear_relu_stack.4.bias", "linear_relu_stack.2.weight", "linear_relu_stack.2.bias". 

In [ ]:
arr = np.array(y_pred.round())

In [ ]:
pred = y_pred.argmax(1)


In [ ]:
ans = np.array(Y1)

In [ ]:
pred = np.array(pred)


In [ ]:
ans = np.array(ans)

In [ ]:
ans == pred

array([False,  True, False, ...,  True,  True, False])

In [ ]:
(ans == pred).mean()

0.43488333333333334

In [ ]:
from PIL import Image
from numpy import asarray


In [ ]:
img = Image.open('data.jpg')

# asarray() class is used to convert
# PIL images into NumPy arrays
numpydata = asarray(img)

In [ ]:

import skimage.io as lo
from skimage import util
import cv2
import PIL
img = lo.imread("data3.jpg")
img = util.invert(img)
img_arr = np.array(img)
#img_arr = img_arr.flatten()

# type(img_arr)
# img_arr = img_arr.astype('float64')
# img = PIL.Image.open('data3.jpg')
# img = util.invert(img)
# arr = np.array(img)
# arr[0][0][0] = 128

# img = PIL.Image.fromarray(np.uint8(arr))
gray = cv2.cvtColor(img_arr, cv2.COLOR_BGR2GRAY)
gray = np.expand_dims(gray, 2)
gray.shape
some_digit = gray.reshape(28,28)

In [ ]:
img2 = some_digit
testneq = torch.from_numpy(img2.astype('float32').reshape(1,28,28))

In [ ]:
Xtest.shape

torch.Size([60000, 28, 28])

In [ ]:

with torch.no_grad():
  y_pred = model(testneq)

In [ ]:
y_pred.argmax(1)

tensor([3])